// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package proc

import (
	"github.com/google/wire"
	"github.com/noaway/tutorial/config"
	"github.com/noaway/tutorial/internal/svc"
	"github.com/noaway/tutorial/provider"
	"github.com/noaway/tutorial/service"
	"github.com/noaway/tutorial/web"
	"github.com/sirupsen/logrus"
	"net"
	"net/http"
)

// Injectors from proc.go:

func InitWeb() (http.Handler, error) {
	userProvider := &provider.UserProvider{}
	userService := &service.UserService{
		Users: userProvider,
	}
	handler, err := web.InitWeb(userService)
	if err != nil {
		return nil, err
	}
	return handler, nil
}

func GetConfig(filename string) *config.Configuration {
	configuration := config.NewConfigure(filename)
	return configuration
}

// proc.go:

var Set = wire.NewSet(config.NewConfigure, wire.Struct(new(provider.UserProvider)), wire.Bind(new(service.Users), new(*provider.UserProvider)), wire.Struct(new(service.UserService), "Users"), web.InitWeb)

type Proc struct {
	httpService svc.HTTPService
}

func (p *Proc) Init() (e error) {
	return nil
}

func (p *Proc) Start() error {
	conf := GetConfig("/Users/noaway/workspace/tutorial/config.conf")
	httpListener, err := net.Listen("tcp", conf.Server.HttpAddr)
	if err != nil {
		return err
	}
	logrus.Info("addr: ", conf.Server.HttpAddr)
	handler, err := InitWeb()
	if err != nil {
		return err
	}

	return p.httpService.Service(httpListener, handler)
}

func (p *Proc) Stop() error {
	p.httpService.Shutdown()
	return nil
}
